apiVersion: v1
kind: Namespace
metadata:
  name: admin-service
  labels:
    name: admin-service
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: admin-service
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: admin-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage